output: api.gen.go
package: twitchApi
output-options:
  skip-prune: true
  user-templates:
    strict/strict-responses.tmpl: "templates/strict-responses.go.tmpl"
    client-with-responses.tmpl: "templates/client-with-responses.go.tmpl"
    client.tmpl: "templates/client.go.tmpl"
    imports.tmpl: "templates/imports.go.tmpl"
    typedef.tmpl: "templates/typedef.go.tmpl"

generate:
  client: true
  models: true
  embedded-spec: true
