output: api.gen.go
package: api
output-options:
  skip-prune: true
  user-templates:
    #LOCAL
    # echo/echo-interface.tmpl: "../../oapi-templates/echo/echo-interface.go.tmpl"
    # echo/echo-register.tmpl: "../../oapi-templates/echo/echo-register.go.tmpl"
    # echo/echo-wrappers.tmpl: "../../oapi-templates/echo/echo-wrappers.go.tmpl"
    # gorm/gorm-dataloader.go.tmpl: "../../oapi-templates/gorm/gorm-dataloader.go.tmpl"
    # gorm/gorm-impl.go.tmpl: "../../oapi-templates/gorm/gorm-impl.go.tmpl"
    # gorm/gorm-interface.go.tmpl: "../../oapi-templates/gorm/gorm-interface.go.tmpl"
    # gorm/gorm.go.tmpl: "../../oapi-templates/gorm/gorm.go.tmpl"
    # strict/strict-echo.tmpl: "../../oapi-templates/strict/strict-echo.go.tmpl"
    # strict/strict-gin.tmpl: "../../oapi-templates/strict/strict-gin.go.tmpl"
    # strict/strict-http.tmpl: "../../oapi-templates/strict/strict-http.go.tmpl"
    # strict/strict-interface.tmpl: "../../oapi-templates/strict/strict-interface.go.tmpl"
    # strict/strict-responses.tmpl: "../../oapi-templates/strict/strict-responses.go.tmpl"
    # additional-properties.tmpl: "../../oapi-templates/additional-properties.go.tmpl"
    # client.tmpl: "../../oapi-templates/client.go.tmpl"
    # client-with-responses.tmpl: "../../oapi-templates/client-with-responses.go.tmpl"
    # constants.tmpl: "../../oapi-templates/constants.go.tmpl"
    # imports.tmpl: "../../oapi-templates/imports.go.tmpl"
    # inline.tmpl: "../../oapi-templates/inline.go.tmpl"
    # param-types.tmpl: "../../oapi-templates/param-types.go.tmpl"
    # request-bodies.tmpl: "../../oapi-templates/request-bodies.go.tmpl"
    # typedef.tmpl: "../../oapi-templates/typedef.go.tmpl"
    # union-and-additional-properties.tmpl: "../../oapi-templates/union-and-additional-properties.go.tmpl"
    # union.tmpl: "../../oapi-templates/union.go.tmpl"

    #Remote
    echo/echo-interface.tmpl: "https://raw.githubusercontent.com/streemtech/oapi-templates/main/echo/echo-interface.go.tmpl"
    echo/echo-register.tmpl: "https://raw.githubusercontent.com/streemtech/oapi-templates/main/echo/echo-register.go.tmpl"
    echo/echo-wrappers.tmpl: "https://raw.githubusercontent.com/streemtech/oapi-templates/main/echo/echo-wrappers.go.tmpl"
    gorm/gorm-dataloader.go.tmpl: "https://raw.githubusercontent.com/streemtech/oapi-templates/main/gorm/gorm-dataloader.go.tmpl"
    gorm/gorm-impl.go.tmpl: "https://raw.githubusercontent.com/streemtech/oapi-templates/main/gorm/gorm-impl.go.tmpl"
    gorm/gorm-interface.go.tmpl: "https://raw.githubusercontent.com/streemtech/oapi-templates/main/gorm/gorm-interface.go.tmpl"
    gorm/gorm.go.tmpl: "https://raw.githubusercontent.com/streemtech/oapi-templates/main/gorm/gorm.go.tmpl"
    strict/strict-echo.tmpl: "https://raw.githubusercontent.com/streemtech/oapi-templates/main/strict/strict-echo.go.tmpl"
    strict/strict-gin.tmpl: "https://raw.githubusercontent.com/streemtech/oapi-templates/main/strict/strict-gin.go.tmpl"
    strict/strict-http.tmpl: "https://raw.githubusercontent.com/streemtech/oapi-templates/main/strict/strict-http.go.tmpl"
    strict/strict-interface.tmpl: "https://raw.githubusercontent.com/streemtech/oapi-templates/main/strict/strict-interface.go.tmpl"
    strict/strict-responses.tmpl: "https://raw.githubusercontent.com/streemtech/oapi-templates/main/strict/strict-responses.go.tmpl"
    additional-properties.tmpl: "https://raw.githubusercontent.com/streemtech/oapi-templates/main/additional-properties.go.tmpl"
    client.tmpl: "https://raw.githubusercontent.com/streemtech/oapi-templates/main/client.go.tmpl"
    client-with-responses.tmpl: "https://raw.githubusercontent.com/streemtech/oapi-templates/main/client-with-responses.go.tmpl"
    constants.tmpl: "https://raw.githubusercontent.com/streemtech/oapi-templates/main/constants.go.tmpl"
    imports.tmpl: "https://raw.githubusercontent.com/streemtech/oapi-templates/main/imports.go.tmpl"
    inline.tmpl: "https://raw.githubusercontent.com/streemtech/oapi-templates/main/inline.go.tmpl"
    param-types.tmpl: "https://raw.githubusercontent.com/streemtech/oapi-templates/main/param-types.go.tmpl"
    request-bodies.tmpl: "https://raw.githubusercontent.com/streemtech/oapi-templates/main/request-bodies.go.tmpl"
    typedef.tmpl: "https://raw.githubusercontent.com/streemtech/oapi-templates/main/typedef.go.tmpl"
    union-and-additional-properties.tmpl: "https://raw.githubusercontent.com/streemtech/oapi-templates/main/union-and-additional-properties.go.tmpl"
    union.tmpl: "https://raw.githubusercontent.com/streemtech/oapi-templates/main/union.go.tmpl"
generate:
  client: true
  strict-server: true
  echo-server: true
  models: true
  embedded-spec: true
